class CityOption {
  final String title;
  final String value;

  const CityOption({required this.title, required this.value});
}

class GovernateOption {
  final String code;
  final String title;
  final List<CityOption> cities;

  const GovernateOption({
    required this.code,
    required this.title,
    required this.cities,
  });
}

// Converted from governates.js
const List<GovernateOption> kGovernates = [
  GovernateOption(
    code: 'KSA',
    title: 'السعودية',
    cities: [
      CityOption(title: 'عقيق', value: 'Aqiq'),
      CityOption(title: 'عطالله', value: 'Atawlah'),
      CityOption(title: 'الباحة', value: 'Baha'),
      CityOption(title: 'بلجرشي', value: 'Baljurashi'),
      CityOption(title: 'المندق', value: 'Mandaq'),
      CityOption(title: 'المظيلف', value: 'Mudhaylif'),
      CityOption(title: 'المخواة', value: 'Mukhwah'),
      CityOption(title: 'قلوة', value: 'Qilwah'),
      CityOption(title: 'القنفذة', value: 'Qunfudhah'),
      CityOption(title: 'الجوف', value: 'Al Jouf'),
      CityOption(title: 'دومة الجندل', value: 'Dawmat Al Jandal'),
      CityOption(title: 'سكاكا', value: 'Skakah'),
      CityOption(title: 'باشوت', value: 'Bashayer'),
      CityOption(title: 'بللسمر', value: 'Bellasmar'),
      CityOption(title: 'النماص', value: 'Namas'),
      CityOption(title: 'سبت العلايا', value: 'Sapt Al Alaya'),
      CityOption(title: 'تنومة', value: 'Tanumah'),
      CityOption(title: 'عين دار', value: 'Ain Dar'),
      CityOption(title: 'عنك', value: 'Anak'),
      CityOption(title: 'جسر البحرين', value: 'Bahrain Causeway'),
      CityOption(title: 'بقيق', value: 'Buqaiq'),
      CityOption(title: 'الدمام', value: 'Dammam'),
      CityOption(title: 'مطار الدمام', value: 'Dammam Airport'),
      CityOption(title: 'الظهران', value: 'Dhahran'),
      CityOption(title: 'الجبيل', value: 'Jubail'),
      CityOption(title: 'الخفجي', value: 'Khafji'),
      CityOption(title: 'الخبر', value: 'Khubar'),
      CityOption(title: 'منيفة', value: 'Muneefa'),
      CityOption(title: 'النعيرية', value: 'Nairiyah'),
      CityOption(title: 'قرية العليا', value: 'Qarya Al Uliya'),
      CityOption(title: 'القطيف', value: 'Qatif'),
      CityOption(title: 'رحيمة', value: 'Rahima'),
      CityOption(title: 'رأس تنورة', value: 'Ras Tannurah'),
      CityOption(title: 'صفوى', value: 'Safwa'),
      CityOption(title: 'سيرة', value: 'Saira'),
      CityOption(title: 'سيهات', value: 'Sayhat'),
      CityOption(title: 'شدقم', value: 'Shedgum'),
      CityOption(title: 'تناجيب', value: 'Tanajib'),
      CityOption(title: 'تاروت (دارين)', value: 'Tarut (Darin)'),
      CityOption(title: 'الثقبة', value: 'Thqbah'),
      CityOption(title: 'العضيلية', value: 'Udhayliyah'),
      CityOption(title: 'عثمانية', value: 'Uthmaniyah'),
      CityOption(title: 'نجران', value: 'Najran'),
      CityOption(title: 'شرورة', value: 'Sharourah'),
      CityOption(title: 'وادي الدواسر', value: 'Wadi Al-Dawasir'),
      CityOption(title: 'البدايع', value: 'Badaya'),
      CityOption(title: 'البكيرية', value: 'Bukayriyah'),
      CityOption(title: 'بريدة', value: 'Buraydah'),
      CityOption(title: 'الدخنة', value: 'Dukhnah'),
      CityOption(title: 'الخبراء', value: 'Khabra'),
      CityOption(title: 'المذنب', value: 'Midhnab'),
      CityOption(title: 'النبهانية', value: 'Nabhaniah'),
      CityOption(title: 'نفي', value: 'Nifi'),
      CityOption(title: 'مطار القصيم', value: 'Qaseem Airport'),
      CityOption(title: 'رفيعة الغمش', value: 'Rafayaa Al Gimsh'),
      CityOption(title: 'الرس', value: 'Rass'),
      CityOption(title: 'رياض الخبراء', value: 'Riyadh Al Khabra'),
      CityOption(title: 'ساجر', value: 'Sajir'),
      CityOption(title: 'عنيزة', value: 'Unayzah'),
      CityOption(title: 'عقلة الصقور', value: 'Uqlat As Suqur'),
      CityOption(title: 'عيون الجواء', value: 'Uyun Al Jiwa'),
      CityOption(title: 'أبو عريش', value: 'Abu Arish'),
      CityOption(title: 'أحد المسارحة', value: 'Ahad Al Masarhah'),
      CityOption(title: 'الدائر', value: 'Al Dayer'),
      CityOption(title: 'الطوال', value: 'At Tuwal'),
      CityOption(title: 'بني مالك', value: 'Bani Malek'),
      CityOption(title: 'بيش', value: 'Baysh'),
      CityOption(title: 'الدرب', value: 'Darb'),
      CityOption(title: 'ضمد', value: 'Dhamad'),
      CityOption(title: 'فرسان', value: 'Farasan'),
      CityOption(title: 'جازان', value: 'Jazan'),
      CityOption(title: 'صبياء', value: 'Sabya'),
      CityOption(title: 'صامطة', value: 'Samtah'),
      CityOption(title: 'الشقيق', value: 'Shuqayq'),
      CityOption(title: 'حائل', value: 'Hail'),
      CityOption(title: 'سائرة', value: 'Sayirah'),
      CityOption(title: 'الروقي', value: 'Al Ruqi'),
      CityOption(title: 'حفر الباطن', value: 'Hafar Al Baten'),
      CityOption(title: 'مدينة الملك خالد', value: 'King Khalid City'),
      CityOption(title: 'القيصومة', value: 'Qaysumah'),
      CityOption(title: 'رفحاء', value: 'Rafha'),
      CityOption(title: 'سعرار', value: 'Sarrar'),
      CityOption(title: 'الأحساء', value: 'Al Ahsa'),
      CityOption(title: 'العيون', value: 'Al Ayun'),
      CityOption(title: 'الجفر', value: 'Al Jafr'),
      CityOption(title: 'بطحاء', value: 'Batha'),
      CityOption(title: 'الهفوف', value: 'Hufuf'),
      CityOption(title: 'المبرز', value: 'Mubarraz'),
      CityOption(title: 'سلوى', value: 'Salwa'),
      CityOption(title: 'بدر', value: 'Badr'),
      CityOption(title: 'بحرة', value: 'Bahrah'),
      CityOption(title: 'جدة', value: 'Jeddah'),
      CityOption(title: 'مطار جدة', value: 'Jeddah Airport'),
      CityOption(title: 'كامل', value: 'Kamil'),
      CityOption(title: 'خليص', value: 'Khulais'),
      CityOption(title: 'الليث', value: 'Lith'),
      CityOption(title: 'مستورة', value: 'Masturah'),
      CityOption(title: 'رابغ', value: 'Rabigh'),
      CityOption(title: 'الشعيبة', value: 'Shaibah'),
      CityOption(title: 'ثول', value: 'Thuwal'),
      CityOption(title: 'أبها', value: 'Abha'),
      CityOption(title: 'أحد رفيدة', value: 'Ahad Rafidah'),
      CityOption(title: 'بارق', value: 'Bariq'),
      CityOption(title: 'بيشة', value: 'Bishah'),
      CityOption(title: 'ظهران الجنوب', value: 'Dhahran Al Janoub'),
      CityOption(title: 'جاش', value: 'Jash'),
      CityOption(title: 'خميس مشيط', value: 'Khamis Mushayt'),
      CityOption(title: 'مجاردة', value: 'Majardah'),
      CityOption(title: 'محايل', value: 'Muhayil'),
      CityOption(title: 'نقيع', value: 'Nakeea'),
      CityOption(title: 'رجال ألمع', value: 'Rijal Almaa'),
      CityOption(title: 'سراة عبيدة', value: 'Sarat Abida'),
      CityOption(title: 'طريب', value: 'Tarib'),
      CityOption(title: 'تثليث', value: 'Tathlith'),
      CityOption(title: 'وادي بن هشبل', value: 'Wadi Bin Hashbal'),
      CityOption(title: 'جموم', value: 'Jamoum'),
      CityOption(title: 'مكة', value: 'Makkah'),
      CityOption(title: 'حنكية', value: 'Hanakiyah'),
      CityOption(title: 'خيبر', value: 'Khayber'),
      CityOption(title: 'المدينة المنورة', value: 'Madinah'),
      CityOption(title: 'مهد الذهب', value: 'Mahd Ad Dhahab'),
      CityOption(title: 'العلا', value: 'Ula'),
      CityOption(title: 'عفيف', value: 'Afif'),
      CityOption(title: 'الارتوازية', value: 'Artawiyah'),
      CityOption(title: 'بجادية', value: 'Bijadiyah'),
      CityOption(title: 'الدودامي', value: 'Duwadimi'),
      CityOption(title: 'غاط', value: 'Ghat'),
      CityOption(title: 'حوطة سدير', value: 'Hawtat Sudayr'),
      CityOption(title: 'المجمعة', value: 'Majmaah'),
      CityOption(title: 'شقراء', value: 'Shaqra'),
      CityOption(title: 'الزلفي', value: 'Zulfi'),
      CityOption(title: 'عرعر', value: 'Arar'),
      CityOption(title: 'جديدة عرعر', value: 'Jadidah Arar'),
      CityOption(title: 'الأفلاج (ليلى)', value: 'Al Aflaj (Layla)'),
      CityOption(title: 'ضرما', value: 'Dhurma'),
      CityOption(title: 'دلم', value: 'Dilam'),
      CityOption(title: 'الدرعية', value: 'Diriyah'),
      CityOption(title: 'حوطة بني تميم', value: 'Hawtat Bani Tamim'),
      CityOption(title: 'الحائر', value: 'Hayer'),
      CityOption(title: 'حريملاء', value: 'Huraymila'),
      CityOption(title: 'الخرج', value: 'Kharj'),
      CityOption(title: 'مزاحمية', value: 'Muzahmiyah'),
      CityOption(title: 'قويعية', value: 'Quwayiyah'),
      CityOption(title: 'رنية', value: 'Ranyah'),
      CityOption(title: 'الرياض', value: 'Riyadh'),
      CityOption(title: 'مطار الرياض', value: 'Riyadh Airport'),
      CityOption(title: 'رماح', value: 'Rumah'),
      CityOption(title: 'رويدة', value: 'Ruwaidah'),
      CityOption(title: 'ضرماء', value: 'Dhalim'),
      CityOption(title: 'الخرمة', value: 'Khurmah'),
      CityOption(title: 'المويه', value: 'Muwayh'),
      CityOption(title: 'رنية', value: 'Ranyah'),
      CityOption(title: 'السيّل الكبير', value: 'Sayl Al Kabir'),
      CityOption(title: 'الطائف', value: 'Taif'),
      CityOption(title: 'تربة', value: 'Turbah'),
      CityOption(title: 'تربة (مكة)', value: 'Turbah (Makkah)'),
      CityOption(title: 'بد', value: 'Bad'),
      CityOption(title: 'ضباء', value: 'Dhuba'),
      CityOption(title: 'حالت عمار', value: 'Halit Ammar'),
      CityOption(title: 'حقل', value: 'Haql'),
      CityOption(title: 'تبوك', value: 'Tabuk'),
      CityOption(title: 'تيماء', value: 'Taima'),
      CityOption(title: 'حديثة', value: 'Haditha'),
      CityOption(title: 'القريات', value: 'Qurayyat'),
      CityOption(title: 'طبرجل', value: 'Tabarjal'),
      CityOption(title: 'طريف', value: 'Turayf'),
      CityOption(title: 'خماسين', value: 'Khamasin'),
      CityOption(title: 'السليل', value: 'Sulayyil'),
      CityOption(title: 'بدر حنين', value: 'Badar Hunain'),
      CityOption(title: 'أملج', value: 'Ummlujj'),
      CityOption(title: 'الوجه', value: 'Wajh'),
      CityOption(title: 'ينبع', value: 'Yanbu'),
      CityOption(title: 'القصيم', value: 'Qaseem'),
    ],
  ),
  GovernateOption(
    code: 'UAE',
    title: 'الامارات',
    cities: [
      CityOption(title: 'العين', value: 'Al Ain'),
      CityOption(title: 'أبو ظبي', value: 'Abu Dhabi'),
      CityOption(title: 'دبي', value: 'Dubai'),
      CityOption(title: 'الفجيرة', value: 'Fujairah'),
      CityOption(title: 'عجمان', value: 'Ajman'),
      CityOption(title: 'أم القيوين', value: 'Umm Al Quwain'),
      CityOption(title: 'رأس الخيمة', value: 'Ras al Khaymah'),
      CityOption(title: 'الشارقة', value: 'Sharjah'),
    ],
  ),
  GovernateOption(
    code: 'Bahrain',
    title: 'البحرين',
    cities: [
      CityOption(title: 'المنامة', value: 'Manama'),
      CityOption(title: 'البديع', value: 'Budaiya'),
      CityOption(title: 'البسيتين', value: 'BUSAITEEN'),
      CityOption(title: 'الحد', value: 'Hidd'),
      CityOption(title: 'مدينة حمد', value: 'HAMADTOWN'),
      CityOption(title: 'هملة', value: 'HAMALA'),
      CityOption(title: 'مدينة عيسى', value: 'ISATOWN'),
      CityOption(title: 'الجفير', value: 'JUFFAIR'),
      CityOption(title: 'المحرق', value: 'Muharraq'),
      CityOption(title: 'ميناء سلمان', value: 'MINA SALMAN'),
      CityOption(title: 'الرفاع', value: 'RIFFA'),
      CityOption(title: 'سار', value: 'SAAR'),
      CityOption(title: 'السيف', value: 'SEEF'),
      CityOption(title: 'سترة', value: 'SITRA'),
      CityOption(title: 'توبلي', value: 'TUBLI'),
    ],
  ),
  GovernateOption(
    code: 'Egypt',
    title: 'مصر',
    cities: [
      CityOption(title: 'الإسكندرية', value: 'Alexandria'),
      CityOption(title: 'أسيوط', value: 'Assiout'),
      CityOption(title: 'أسوان', value: 'Aswan'),
      CityOption(title: 'البحيرة', value: 'Behira'),
      CityOption(title: 'بني سويف', value: 'Beni Souif'),
      CityOption(title: 'القاهرة', value: 'Cairo'),
      CityOption(title: 'القاهرة الكبرى', value: 'Cairo Sub.'),
      CityOption(title: 'الدقهلية', value: 'Dakhlia'),
      CityOption(title: 'دمياط', value: 'Demiatta'),
      CityOption(title: 'الفيوم', value: 'Fayoum'),
      CityOption(title: 'الغربية', value: 'Gharbia'),
      CityOption(title: 'الإسماعيلية', value: 'Ismailia'),
      CityOption(title: 'كفر الشيخ', value: 'Kafr Elshiekh'),
      CityOption(title: 'الأقصر', value: 'Luxor'),
      CityOption(title: 'المنيا', value: 'Minia'),
      CityOption(title: 'المنوفية', value: 'Menoufia'),
      CityOption(title: 'مرسى مطروح', value: 'Marsa Matrouh'),
      CityOption(title: 'شمال سيناء', value: 'North Sinai'),
      CityOption(title: 'الوادي الجديد', value: 'New Valley'),
      CityOption(title: 'بورسعيد', value: 'Port Said'),
      CityOption(title: 'القليوبية', value: 'Qalioubia'),
      CityOption(title: 'قنا', value: 'Qena'),
      CityOption(title: 'البحر الأحمر', value: 'Red Sea'),
      CityOption(title: 'سوهاج', value: 'Sohag'),
      CityOption(title: 'الشرقية', value: 'Sharkia'),
      CityOption(title: 'جنوب سيناء', value: 'South Sinai'),
      CityOption(title: 'السويس', value: 'Suez'),
    ],
  ),
  GovernateOption(
    code: 'Oman',
    title: 'عمان',
    cities: [
      CityOption(title: 'آدم', value: 'ADAM'),
      CityOption(title: 'الخوض', value: 'AL KHOUDH'),
      CityOption(title: 'الخوير', value: 'AL KHUWAIR'),
      CityOption(title: 'الكامل', value: 'AL KAMIL'),
      CityOption(title: 'العامرات', value: 'AMERAT'),
      CityOption(title: 'الأنصب', value: 'AL ANSAB'),
      CityOption(title: 'الوافي', value: 'AWABI'),
      CityOption(title: 'العذيبة', value: 'AZAIBA'),
      CityOption(title: 'بركاء', value: 'BARKA'),
      CityOption(title: 'بداية', value: 'BIDAYA'),
      CityOption(title: 'بدية', value: 'BEDEYA'),
      CityOption(title: 'بهلاء', value: 'BAHLA'),
      CityOption(title: 'بدبد', value: 'BIDBID'),
      CityOption(title: 'بوشر', value: 'BOUSHER'),
      CityOption(title: 'البريمي', value: 'BURAIMI'),
      CityOption(title: 'دارسيت', value: 'DARSAIT'),
      CityOption(title: 'ضنك', value: 'DHANK'),
      CityOption(title: 'الدقم', value: 'DUQUM'),
      CityOption(title: 'فنجاء', value: 'FANJA'),
      CityOption(title: 'فلاج', value: 'FALAJ'),
      CityOption(title: 'غلا', value: 'GHALA'),
      CityOption(title: 'الغبرة', value: 'GHOBRA'),
      CityOption(title: 'هيماء', value: 'HAIMA'),
      CityOption(title: 'حلبي', value: 'HALBAN'),
      CityOption(title: 'حيل', value: 'HAIL'),
      CityOption(title: 'الحمراء', value: 'HAMRA'),
      CityOption(title: 'الحمرية', value: 'HAMRIYA'),
      CityOption(title: 'عبري', value: 'IBRI'),
      CityOption(title: 'إبراء', value: 'IBRA'),
      CityOption(title: 'إزكي', value: 'IZKI'),
      CityOption(title: 'جعلان بني حسن', value: 'JALAN BU HASSAN'),
      CityOption(title: 'جفنين', value: 'JIFNAIN'),
      CityOption(title: 'جعلان', value: 'JALAN'),
      CityOption(title: 'كامل', value: 'KAMIL'),
      CityOption(title: 'خصب', value: 'KHASAB'),
      CityOption(title: 'الخضراء', value: 'KHADRA'),
      CityOption(title: 'الخابورة', value: 'KHABOURAH'),
      CityOption(title: 'لوى', value: 'LIWA'),
      CityOption(title: 'لزوغ', value: 'LIZOUGH'),
      CityOption(title: 'المعبيلة', value: 'MABELLA'),
      CityOption(title: 'محوت', value: 'MAHOOT'),
      CityOption(title: 'مدينة الإعلام', value: 'MADINAT AL ILLAM'),
      CityOption(title: 'مصيرة', value: 'MASHEERA'),
      CityOption(title: 'الموالح', value: 'MAWELLAH'),
      CityOption(title: 'مسقط', value: 'MUSCAT'),
      CityOption(title: 'منتراب', value: 'MINTRIB'),
      CityOption(title: 'مصفاة', value: 'MISFAH'),
      CityOption(title: 'منح', value: 'MANAH'),
      CityOption(title: 'مدينة السلطان قابوس', value: 'MADINAT SULTAN QABOOS'),
      CityOption(title: 'مرباط', value: 'MARBATH'),
      CityOption(title: 'المضيبي', value: 'MUDHAIBI'),
      CityOption(title: 'الملاحة', value: 'MULLADHA'),
      CityOption(title: 'المصنعة', value: 'MUSSNAH'),
      CityOption(title: 'مطرح', value: 'MUTTRAH'),
      CityOption(title: 'نخل', value: 'NAKHAL'),
      CityOption(title: 'نزوى', value: 'NIZWA'),
      CityOption(title: 'القُرم', value: 'QURUM'),
      CityOption(title: 'الرستاق', value: 'RUSTAQ'),
      CityOption(title: 'رميس', value: 'RUMAIS'),
      CityOption(title: 'رسيل', value: 'RUSAYL'),
      CityOption(title: 'روي', value: 'RUWI'),
      CityOption(title: 'سماد الشان', value: 'SAMAD AL SHAN'),
      CityOption(title: 'السيب', value: 'SEEB'),
      CityOption(title: 'شناص', value: 'SHINAS'),
      CityOption(title: 'صحم', value: 'SAHAM'),
      CityOption(title: 'سداب', value: 'SIDAB'),
      CityOption(title: 'صلالة', value: 'SALALAH'),
      CityOption(title: 'سمائل', value: 'SUMAIL'),
      CityOption(title: 'سناو', value: 'SINAW'),
      CityOption(title: 'صحار', value: 'SOHAR'),
      CityOption(title: 'صور', value: 'SUR'),
      CityOption(title: 'السويق', value: 'SUWAIQ'),
      CityOption(title: 'ثرمد', value: 'THARMAD'),
      CityOption(title: 'ثمريت', value: 'THUMRAIT'),
      CityOption(title: 'وادي كبير', value: 'WADI KABIR'),
      CityOption(title: 'وادي عدي', value: 'WADI ADAI'),
      CityOption(title: 'وادي حطاط', value: 'WADI HATAT'),
      CityOption(title: 'الوطية', value: 'WATTAYA'),
      CityOption(title: 'ودام', value: 'WUDAM'),
      CityOption(title: 'ينقل', value: 'YANQUL'),
    ],
  ),
  GovernateOption(
    code: 'Kuwait',
    title: 'الكويت',
    cities: [
      CityOption(title: 'الأحمدي', value: 'AL AHMADI'),
      CityOption(title: 'العاصمة', value: 'AL AASMAH'),
      CityOption(title: 'الفروانية', value: 'FARWANIYAH'),
      CityOption(title: 'حولي', value: 'HAWALLY'),
      CityOption(title: 'الجهراء', value: 'AL JAHRA'),
      CityOption(title: 'مبارك الكبير', value: 'MUBARAK AL KABEER'),
    ],
  ),
  GovernateOption(
    code: 'Qatar',
    title: 'قطر',
    cities: [
      CityOption(title: 'الدوحة', value: 'Doha'),
      CityOption(title: 'الوكرة', value: 'Al Wakrah'),
      CityOption(title: 'الخور', value: 'Al Khor'),
      CityOption(title: 'الريان', value: 'Al Rayyan'),
      CityOption(title: 'أم صلال', value: 'Umm Salal'),
      CityOption(title: 'الذخيرة', value: 'Al Thakhira'),
      CityOption(title: 'الشمال', value: 'Al Shamal'),
      CityOption(title: 'دخان', value: 'Dukhan'),
      CityOption(title: 'مسيعيد', value: 'Mesaieed'),
      CityOption(title: 'الغويرية', value: 'Al Ghuwairiya'),
      CityOption(title: 'الجميلية', value: 'Al Jumaliyah'),
      CityOption(title: 'لوسيل', value: 'Lusail'),
    ],
  ),
];

const List<({String code, String nameEn, String nameAr})> countries = [
  (code: 'SA', nameEn: 'Saudi Arabia', nameAr: 'السعودية'),
  (code: 'AE', nameEn: 'United Arab Emirates', nameAr: 'الإمارات'),
  (code: 'KW', nameEn: 'Kuwait', nameAr: 'الكويت'),
  (code: 'QA', nameEn: 'Qatar', nameAr: 'قطر'),
  (code: 'BH', nameEn: 'Bahrain', nameAr: 'البحرين'),
  (code: 'OM', nameEn: 'Oman', nameAr: 'عُمان'),
  (code: 'EG', nameEn: 'Egypt', nameAr: 'مصر'),
  (code: 'JO', nameEn: 'Jordan', nameAr: 'الأردن'),
  (code: 'IQ', nameEn: 'Iraq', nameAr: 'العراق'),
  (code: 'SY', nameEn: 'Syria', nameAr: 'سوريا'),
  (code: 'LB', nameEn: 'Lebanon', nameAr: 'لبنان'),
  (code: 'PS', nameEn: 'Palestine', nameAr: 'فلسطين'),
  (code: 'YE', nameEn: 'Yemen', nameAr: 'اليمن'),
  (code: 'LY', nameEn: 'Libya', nameAr: 'ليبيا'),
  (code: 'SD', nameEn: 'Sudan', nameAr: 'السودان'),
  (code: 'TN', nameEn: 'Tunisia', nameAr: 'تونس'),
  (code: 'DZ', nameEn: 'Algeria', nameAr: 'الجزائر'),
  (code: 'MA', nameEn: 'Morocco', nameAr: 'المغرب'),
  (code: 'TR', nameEn: 'Turkey', nameAr: 'تركيا'),
  (code: 'US', nameEn: 'United States', nameAr: 'الولايات المتحدة'),
  (code: 'GB', nameEn: 'United Kingdom', nameAr: 'بريطانيا'),
  (code: 'FR', nameEn: 'France', nameAr: 'فرنسا'),
  (code: 'DE', nameEn: 'Germany', nameAr: 'ألمانيا'),
  (code: 'IN', nameEn: 'India', nameAr: 'الهند'),
  (code: 'PK', nameEn: 'Pakistan', nameAr: 'باكستان'),
  (code: 'BD', nameEn: 'Bangladesh', nameAr: 'بنغلاديش'),
  (code: 'PH', nameEn: 'Philippines', nameAr: 'الفلبين'),
  (code: 'ID', nameEn: 'Indonesia', nameAr: 'إندونيسيا'),
  (code: 'MY', nameEn: 'Malaysia', nameAr: 'ماليزيا'),
  (code: 'CN', nameEn: 'China', nameAr: 'الصين'),
];
