{
  "formatVersion": "1.1",
  "component": {
    "group": "net.geidea",
    "module": "PGW-SDK",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "PGW-SDK-1.0.0.aar",
          "url": "PGW-SDK-1.0.0.aar",
          "size": 2983502,
          "sha512": "30f91c92af0034d83dc20618fc4338c87ac5dc17221ef59575f4229b93cc6eadcc561e1b0e2c404e659c7847a6def4dafc0781ac5a8b1c312b4810cfe7b6aad1",
          "sha256": "44f8eafebdc1b7fbfdf01911a09815c6728b530a2ff000d29d554766e1be4c60",
          "sha1": "44ed5c71a9d9e5c8f9ec1873c1aea6ccce889493",
          "md5": "6689ba2ff2b8c4ef5d9cef57cb3139ee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "PGW-SDK-1.0.0.aar",
          "url": "PGW-SDK-1.0.0.aar",
          "size": 2983502,
          "sha512": "30f91c92af0034d83dc20618fc4338c87ac5dc17221ef59575f4229b93cc6eadcc561e1b0e2c404e659c7847a6def4dafc0781ac5a8b1c312b4810cfe7b6aad1",
          "sha256": "44f8eafebdc1b7fbfdf01911a09815c6728b530a2ff000d29d554766e1be4c60",
          "sha1": "44ed5c71a9d9e5c8f9ec1873c1aea6ccce889493",
          "md5": "6689ba2ff2b8c4ef5d9cef57cb3139ee"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "PGW-SDK-1.0.0-sources.jar",
          "url": "PGW-SDK-1.0.0-sources.jar",
          "size": 390503,
          "sha512": "baedafeb7a6eea99bc9250b2ded456dd856df950467f689beb39f89eb688ef017f73c8dcf8d67e5953465f41a219054357258c91c8f926fe98219f858a608dc7",
          "sha256": "3c73c82f56da7026ac63dd250c20713fbb390f385cf4f39071e187dfab2be170",
          "sha1": "553103f0de808bc66bd0e58ee64f365fa7db0adb",
          "md5": "672bbab895c495cef432999891c6f5ef"
        }
      ]
    }
  ]
}
