# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # 1. Sync certificates and profiles
    match(type: "appstore")
    
    # 2. Ensure Pods are up to date
    cocoapods
    
    # 3. Increment build number
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    
    # 4. Build the app for App Store distribution
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj"
    )

    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "com.deepblue.turathy" => "match AppStore com.deepblue.turathy"
        }
      }
    )
    
    # 5. Upload to TestFlight
    upload_to_testflight
  end
end
